In [37]:
!ls data/

baby-products.csv         grocery-gourmet-food.csv  toys-games.csv
beauty.csv                health-personal-care.csv  train_40k.csv
cat1.csv                  pet-supplies.csv          train_relative_labels.csv


# Top level classifier

In [136]:
from sklearn import *
import csv
import pandas as pd
import pickle
from sklearn.pipeline import Pipeline

In [100]:
clf1 = Pipeline(
    steps=[
        ('tok', feature_extraction.text.TfidfVectorizer(min_df = 3, max_df=0.8, ngram_range=[1,2])),
        ('clf', svm.LinearSVC(penalty='l2', multi_class='ovr', class_weight='balanced'))
    ]
)

clf2 = Pipeline(
    steps=[
        ('tok', feature_extraction.text.TfidfVectorizer(min_df = 3, max_df=0.8, ngram_range=[1,2])),
        ('clf', svm.LinearSVC(penalty='l2', multi_class='ovr', class_weight='balanced'))
    ]
)

In [101]:
df = pd.read_csv('data/train_relative_labels.csv', index_col=False).fillna('n/a'); df.head()

Unnamed: 0   productId                                Title  \
0           0  B000E46LYG  Golden Valley Natural Buffalo Jerky   
1           1  B000GRA6N8                         Westing Game   
2           2  B000GRA6N8                         Westing Game   
3           3  B000GRA6N8                         Westing Game   
4           4  B00000DMDQ    I SPY A is For Jigsaw Puzzle 63pc   

           userId Helpfulness  Score       Time  \
0  A3MQDNGHDJU4MK         0/0    3.0         -1   
1         unknown         0/0    5.0  860630400   
2         unknown         0/0    5.0  883008000   
3         unknown         0/0    5.0  897696000   
4         unknown         2/4    5.0  911865600   

                                                Text                  Cat1  \
0  The description and photo on this product need...  grocery gourmet food   
1  This was a great book!!!! It is well thought t...            toys games   
2  I am a first year teacher, teaching 5th grade....            toys games   
3  I got the book at my bookfair at school lookin...            toys games   
4  Hi! I'm Martine Redman and I created this puzz...            toys games   

           Cat2            Cat3  \
0  meat poultry           jerky   
1         games         unknown   
2         games         unknown   
3         games         unknown   
4       puzzles  jigsaw puzzles   

                                        text_feature  \
0  Golden Valley Natural Buffalo Jerky The descri...   
1  Westing Game This was a great book!!!! It is w...   
2  Westing Game I am a first year teacher, teachi...   
3  Westing Game I got the book at my bookfair at ...   
4  I SPY A is For Jigsaw Puzzle 63pc Hi! I'm Mart...   

  labels-grocery-gourmet-food labels-toys-games labels-beauty  \
0                meat poultry               n/a           n/a   
1                         n/a             games           n/a   
2                         n/a             games           n/a   
3                         n/a             games           n/a   
4                         n/a           puzzles           n/a   

  labels-health-personal-care labels-baby-products labels-pet-supplies  
0                         n/a                  n/a                 n/a  
1                         n/a                  n/a                 n/a  
2                         n/a                  n/a                 n/a  
3                         n/a                  n/a                 n/a  
4                         n/a                  n/a                 n/a

In [102]:
cats = df.Cat1.unique()

In [103]:
train_df, test_df = model_selection.train_test_split(df, train_size=0.8, test_size = 0.2, random_state=1)

In [104]:
clf1.fit(train_df['text_feature'], train_df['Cat1'])

Pipeline(memory=None,
     steps=[('tok', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.8, max_features=None, min_df=3,
        ngram_range=[1, 2], norm='l2', preprocessor=None, smooth_idf=True,
 ...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [105]:
Y_pred = clf1.predict(test_df['text_feature'])
print(metrics.classification_report(test_df['Cat1'], Y_pred))
print(metrics.confusion_matrix(test_df['Cat1'], Y_pred))

                      precision    recall  f1-score   support

       baby products       0.96      0.95      0.96      1161
              beauty       0.92      0.94      0.93      1129
grocery gourmet food       0.93      0.95      0.94       724
health personal care       0.93      0.92      0.93      1946
        pet supplies       0.97      0.96      0.96       957
          toys games       0.97      0.97      0.97      2083

           micro avg       0.95      0.95      0.95      8000
           macro avg       0.95      0.95      0.95      8000
        weighted avg       0.95      0.95      0.95      8000

[[1106    8    0    9    5   33]
 [   3 1058    7   55    2    4]
 [   2    3  690   25    0    4]
 [  13   72   35 1797   14   15]
 [   5    5    4   19  916    8]
 [  19    3    2   24   12 2023]]


In [106]:
clf2.fit(train_df['text_feature'], train_df['Cat2'])

Pipeline(memory=None,
     steps=[('tok', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.8, max_features=None, min_df=3,
        ngram_range=[1, 2], norm='l2', preprocessor=None, smooth_idf=True,
 ...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [147]:
Y_pred = clf2.predict(test_df['text_feature'])
print(metrics.classification_report(test_df['Cat2'], Y_pred))
print(metrics.confusion_matrix(test_df['Cat2'], Y_pred))

                                  precision    recall  f1-score   support

              action toy figures       0.84      0.75      0.79       227
                     arts crafts       0.80      0.91      0.85        67
                 baby child care       0.96      0.79      0.86        28
                       baby food       1.00      0.85      0.92        13
               baby toddler toys       0.71      0.80      0.75       212
                       bath body       0.79      0.75      0.77       112
               bathing skin care       0.82      0.78      0.80        65
                       beverages       0.90      0.93      0.91       168
                           birds       0.90      0.86      0.88        21
                   breads bakery       0.65      0.74      0.69        27
                 breakfast foods       0.90      0.90      0.90        58
                   building toys       0.84      0.86      0.85        97
            bunny rabbit central     

/Users/Viktor/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [148]:
inverted_hier = pickle.load(open('inverted_hier.pkl', 'rb'))

In [152]:
Y_pred_cat = [inverted_hier[y] for y in Y_pred if y != 'n/a']
print(metrics.classification_report(test_df['Cat1'], Y_pred_cat))
print(metrics.confusion_matrix(test_df['Cat1'], Y_pred_cat))

                      precision    recall  f1-score   support

       baby products       0.95      0.97      0.96      1161
              beauty       0.91      0.95      0.93      1129
grocery gourmet food       0.95      0.95      0.95       724
health personal care       0.94      0.92      0.93      1946
        pet supplies       0.97      0.96      0.96       957
          toys games       0.98      0.97      0.97      2083

           micro avg       0.95      0.95      0.95      8000
           macro avg       0.95      0.95      0.95      8000
        weighted avg       0.95      0.95      0.95      8000

[[1122    8    0    9    4   18]
 [   7 1070    7   38    3    4]
 [   0    2  690   22    1    9]
 [  22   78   28 1792   10   16]
 [   8    8    2   20  917    2]
 [  24    4    3   25   15 2012]]


# Sub category classifiers

Instead of training a single classifier for the second level categories in the hierarchy, a valid approach is to train individual classifiers for each category.

In [108]:
subcat_dict = {}
X_train = train_df['text_feature']
X_test = test_df['text_feature']
for c in cats:
    print(c)
    column_name = f"labels-{c.replace(' ', '-')}"
    
    clf = Pipeline(
        steps=[
            ('tok', feature_extraction.text.TfidfVectorizer(min_df = 3, max_df=0.8, ngram_range=[1,2])),
            ('clf', svm.LinearSVC(penalty='l2', multi_class='ovr', class_weight='balanced'))
        ]
    )
    Y_train = train_df[column_name]
    Y_test = test_df[column_name]
    
    clf.fit(X_train, Y_train)
    
    Y_pred = clf.predict(X_test)
    Y_scores = clf.decision_function(X_test)
    
    subcat_dict[c] = {
        "clf": clf
    }
    print(metrics.classification_report(Y_test, Y_pred))
    print("---------------------------------------------")

grocery gourmet food
                                  precision    recall  f1-score   support

                       baby food       1.00      0.69      0.82        13
                       beverages       0.91      0.91      0.91       168
                   breads bakery       0.63      0.70      0.67        27
                 breakfast foods       0.85      0.88      0.86        58
                 candy chocolate       0.87      0.82      0.84        71
         cooking baking supplies       0.40      0.18      0.25        11
                      dairy eggs       0.88      0.78      0.82         9
fresh flowers live indoor plants       1.00      0.78      0.88         9
                   gourmet gifts       1.00      0.50      0.67        16
                           herbs       0.57      0.31      0.40        13
                    meat poultry       0.80      0.67      0.73         6
                    meat seafood       1.00      0.12      0.22         8
                

# Combine models

## Top-down approach
Travers the category hierarchy top down and let each classifier determine where to go next. 

### First level

In [111]:
test_df['cat1_preds'] = clf1.predict(test_df['text_feature']); 

/Users/Viktor/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [112]:
test_df['cat2_preds'] = test_df.apply(lambda x: (subcat_dict[x['cat1_preds']]['clf']).predict([x['text_feature']])[0], axis=1)

/Users/Viktor/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [113]:
test_df.head()

Unnamed: 0   productId  \
3841         3841  B00005UC6D   
12898       12898  B0009XH6SC   
15032       15032  B000P3L7TA   
36781       36781  B0001MIG9Y   
9201         9201  B000127V8G   

                                                   Title          userId  \
3841             Summer Infant Complete Nursery Care Kit  A1JW64B237RTP4   
12898                      Andis Ceramic Clamp Flat Iron   A9FYS670R0KKD   
15032  Splenda No Calorie Sweetener Granular, Individ...  A1O0JH4DF6J0G6   
36781      Pampers Baby Dry Diapers (Packaging May Vary)  A2M63H4RLIUPXY   
9201              Camille Beckman Glycerine Hand Therapy  A18434XIA0I5T1   

      Helpfulness  Score        Time  \
3841          4/5    3.0  1110758400   
12898         0/0    5.0  1203552000   
15032         0/0    5.0  1219881600   
36781         0/0    4.0  1331942400   
9201          1/1    5.0  1176163200   

                                                    Text  \
3841   I received this kit as a gift and I actually u...   
12898  I love my Andis Flat Iron! I initially bought ...   
15032  As I use alot of Splenda, this was a great $$ ...   
36781  Tried a lot of brands and found these to be th...   
9201   I've smelled the Vanilla, Orange, Vanilla Spic...   

                       Cat1                     Cat2  \
3841          baby products        bathing skin care   
12898                beauty                hair care   
15032  grocery gourmet food  cooking baking supplies   
36781         baby products                diapering   
9201                 beauty                skin care   

                           Cat3  \
3841   grooming healthcare kits   
12898             styling tools   
15032         sugar substitutes   
36781        disposable diapers   
9201                hands nails   

                                            text_feature  \
3841   Summer Infant Complete Nursery Care Kit I rece...   
12898  Andis Ceramic Clamp Flat Iron I love my Andis ...   
15032  Splenda No Calorie Sweetener Granular, Individ...   
36781  Pampers Baby Dry Diapers (Packaging May Vary) ...   
9201   Camille Beckman Glycerine Hand Therapy I've sm...   

      labels-grocery-gourmet-food labels-toys-games labels-beauty  \
3841                          n/a               n/a           n/a   
12898                         n/a               n/a     hair care   
15032     cooking baking supplies               n/a           n/a   
36781                         n/a               n/a           n/a   
9201                          n/a               n/a     skin care   

      labels-health-personal-care labels-baby-products labels-pet-supplies  \
3841                          n/a    bathing skin care                 n/a   
12898                         n/a                  n/a                 n/a   
15032                         n/a                  n/a                 n/a   
36781                         n/a            diapering                 n/a   
9201                          n/a                  n/a                 n/a   

                 cat1_preds         cat2_preds  
3841          baby products  bathing skin care  
12898                beauty          hair care  
15032  grocery gourmet food     pantry staples  
36781         baby products          diapering  
9201                 beauty          skin care

In [114]:
print(metrics.classification_report(test_df['Cat1'], test_df['cat1_preds']))
print(metrics.classification_report(test_df['Cat2'], test_df['cat2_preds']))

                      precision    recall  f1-score   support

       baby products       0.96      0.95      0.96      1161
              beauty       0.92      0.94      0.93      1129
grocery gourmet food       0.93      0.95      0.94       724
health personal care       0.93      0.92      0.93      1946
        pet supplies       0.97      0.96      0.96       957
          toys games       0.97      0.97      0.97      2083

           micro avg       0.95      0.95      0.95      8000
           macro avg       0.95      0.95      0.95      8000
        weighted avg       0.95      0.95      0.95      8000

                                  precision    recall  f1-score   support

              action toy figures       0.81      0.74      0.77       227
                     arts crafts       0.84      0.88      0.86        67
                 baby child care       0.95      0.75      0.84        28
                       baby food       1.00      0.62      0.76        13
      

/Users/Viktor/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/Viktor/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


This approach performed worse than simply training a classifier per level in the hierarchy. 

In [120]:
sum(test_df.cat2_preds == 'n/a')

636

In [122]:
print(metrics.classification_report(test_df[test_df.cat2_preds != 'n/a']['Cat1'], test_df[test_df.cat2_preds != 'n/a']['cat1_preds']))
print(metrics.classification_report(test_df[test_df.cat2_preds != 'n/a']['Cat2'], test_df[test_df.cat2_preds != 'n/a']['cat2_preds']))

                      precision    recall  f1-score   support

       baby products       0.98      0.97      0.97      1090
              beauty       0.95      0.96      0.96      1040
grocery gourmet food       0.96      0.98      0.97       647
health personal care       0.97      0.95      0.96      1764
        pet supplies       0.98      0.98      0.98       876
          toys games       0.99      0.99      0.99      1947

           micro avg       0.97      0.97      0.97      7364
           macro avg       0.97      0.97      0.97      7364
        weighted avg       0.97      0.97      0.97      7364

                                  precision    recall  f1-score   support

              action toy figures       0.81      0.78      0.80       215
                     arts crafts       0.84      0.92      0.88        64
                 baby child care       0.95      0.78      0.86        27
                       baby food       1.00      0.89      0.94         9
      

In [135]:
text = "'Har '"
catpred = clf1.predict([text])[0]
subcat_pred = subcat_dict[catpred]['clf'].predict([text])[0]
print(f"Category: {catpred} - Sub category: {subcat_pred}")

Category: health personal care - Sub category: nutrition wellness


## Train subcategory models without data from different super-category

In [153]:
train_df.head()

Unnamed: 0   productId  \
21721       21721  B000TZ8SEQ   
15576       15576  B0002AR15U   
28716       28716  B000HU7WSG   
204           204  B000053033   
36677       36677  B000127VW2   

                                                   Title          userId  \
21721                Little Tikes Discovery Camera Phone   AMPKOVNC7AT84   
15576                     KONG Classic Kong Dog Toy, Red  A1GLFCHN4VIVY9   
28716  Clif Shot Bloks Organic Energy Chews, 2.1-Ounc...   AK4Z02BLY03K9   
204    Pure & Natural Hypoallergenic Bar Soap, 4.5 oz...         unknown   
36677                  Camille Beckman Hand & Shower Gel  A1U48J4YOWOVDV   

      Helpfulness  Score        Time  \
21721         0/0    2.0  1264982400   
15576         1/1    5.0  1223856000   
28716         1/1    4.0  1301529600   
204           3/3    5.0   953424000   
36677         0/0    5.0  1331596800   

                                                    Text  \
21721  My son seems to like this phone okay. But comp...   
15576  This is my dog's favorite, not only becuase it...   
28716  I take these on long runs. I typically don't e...   
204    Winter is hard on my skin and we've had an exc...   
36677  I bought the 8oz White lilac shower gel and I ...   

                       Cat1                   Cat2          Cat3  \
21721            toys games  dress up pretend play  pretend play   
15576          pet supplies                   dogs          toys   
28716  grocery gourmet food             snack food     party mix   
204                  beauty              bath body     cleansers   
36677                beauty              bath body     cleansers   

                                            text_feature  \
21721  Little Tikes Discovery Camera Phone My son see...   
15576  KONG Classic Kong Dog Toy, Red This is my dog'...   
28716  Clif Shot Bloks Organic Energy Chews, 2.1-Ounc...   
204    Pure & Natural Hypoallergenic Bar Soap, 4.5 oz...   
36677  Camille Beckman Hand & Shower Gel I bought the...   

      labels-grocery-gourmet-food      labels-toys-games labels-beauty  \
21721                         n/a  dress up pretend play           n/a   
15576                         n/a                    n/a           n/a   
28716                  snack food                    n/a           n/a   
204                           n/a                    n/a     bath body   
36677                         n/a                    n/a     bath body   

      labels-health-personal-care labels-baby-products labels-pet-supplies  
21721                         n/a                  n/a                 n/a  
15576                         n/a                  n/a                dogs  
28716                         n/a                  n/a                 n/a  
204                           n/a                  n/a                 n/a  
36677                         n/a                  n/a                 n/a

In [ ]:
subcat_dict = {}

for c in cats:
    print(c)
    column_name = f"labels-{c.replace(' ', '-')}"
    
    clf = Pipeline(
        steps=[
            ('tok', feature_extraction.text.TfidfVectorizer(min_df = 3, max_df=0.8, ngram_range=[1,2])),
            ('clf', svm.LinearSVC(penalty='l2', multi_class='ovr', class_weight='balanced'))
        ]
    )
    X_train = train_df[train_df[column_name] != 'n/a'][column_name]
    
    Y_train = train_df[column_name]
    Y_test = test_df[column_name]
    
    clf.fit(X_train, Y_train)
    
    Y_pred = clf.predict(X_test)
    Y_scores = clf.decision_function(X_test)
    
    subcat_dict[c] = {
        "clf": clf
    }
    print(metrics.classification_report(Y_test, Y_pred))
    print("---------------------------------------------")